### ISSUE TITLE
Titles of updates in he admin panel

### ISSUE THREAD

**Issue by kgstew** [reallocate/reallocate#109]
If you view the list of updates in the admin panel they are all listed as "Update, coming soon!"

If we need to remove a specific update from the list it is hard to determine which updates are which. 

Lets change the naming convention for these to be ProjectID-OpportunityID-Datetime then we can search and remove if necessary.

**Comment by j-po** [comment]
In case someone else picks this issue up before I get my working copy working again, the line of code in question is in models.Update.__unicode__(self) .
