### ISSUE TITLE
Fix Facebook Login Bug

### ISSUE THREAD

**Issue by kgstew** [reallocate/reallocate#128]
Login new account with facebook on the One Armenia site is throwing an error.

**Comment by scottzer0** [comment]
this relates to valid domains that the reallocate facebook "app" accepts.  it has some special rules to validate the domains added and it looks like it'll accept "reallocate.onearmenia.org" and "reallocate.herokuapp.com"  which is helpful.  it rejects "freespace.herokuapp.com" and reallocate-staging.herokuapp.com"  i think becuase they down't have "reallocate" as part of the domain surrounded by dots.  the error does allude to a check again a derivative of the canvas url.

good news is, all production domains (*.reallocate.org & reallocate.onearmenia.org) work.   so i'm closing this and noting this issue with some of the herokuapp.com subdomains (just hinders using facebook login on cobranded staging domains).
