### ISSUE TITLE
Get started page

### ISSUE THREAD

**Issue by scottzer0** [reallocate/reallocate#27]
URL: /get-started

initial page giving an brief overview of the reallocate platform and an outline of the steps expected of the user.
- org info
- create project
- create opportunities

**Comment by scottzer0** [comment]
this actually has something up but need to be lushed out with a sexy diagram and some clearer user hand-holding

**Comment by kgstew** [comment]
Added a new overview of the value of the site. Created a workflow to give new project owners an idea of the steps they are about to go through. Added icons and styled the page.
