### ISSUE TITLE
Internal Server error

### ISSUE THREAD

**Issue by Prmavensf** [reallocate/reallocate#55]
Opened project, on (2nd page) new project page, filled out some fields with legit text and then, added an image, (received green check) "next" button at bottom still not highlighted, so went back and added dummy text to unfilled fields (we need to say all fields mandatory btw) ...button highlighted once all fields filled, clicked next, received internal server error...
http://dev.reallocate.org/project/new/?org=13

**Comment by scottzer0** [comment]
fixed bad S3 bucket name for staging instance
