### ISSUE TITLE
Create Browse Projects Page

### ISSUE THREAD

**Issue by kgstew** [reallocate/reallocate#60]
The homepage should be used to display featured projects or a selections of projects based on causes and types. 

We will want a browse page to offer a longer listing of projects to browse based on a filters. Starting with browse all and offering a selection of filters for causes, locations, opportunity types.

**Comment by scottzer0** [comment]
- move home page project to ones marked "featured"
- add "see more project" button below, elsewhere?
- add featured as a status?

**Comment by davidemerritt** [comment]
browse page is impemented for projects (/find-project)
