### ISSUE TITLE
Implement skill and cause tags

### ISSUE THREAD

**Issue by scottzer0** [reallocate/reallocate#8]
- define am initial list of skills
- define an initial list of causes
- add causes UI to project management page
- add skills UI to profile page 
- grab linkedin’s skill taxonomy (audit and load somewhere)

**Comment by kgstew** [comment]
Causes
Advocacy & Human Rights
Animals
Arts & Culture
Board Development
Children & Youth
Community
Computers & Technology
Crisis Support
Disabled
Disaster Relief
Education & Literacy
Emergency & Safety
Employment
Environment
Faith-Based
Health & Medicine
Homeless & Housing
Hunger
Immigrants & Refugees
International
Justice & Legal
LGBT
Media & Broadcasting
Politics
Race & Ethnicity
Science and Technology
Seniors
Sports & Recreation
Veterans & Military Families
Women

**Comment by kgstew** [comment]
Tagging systems!
