### ISSUE TITLE
Auto suggest organization if it already exists

### ISSUE THREAD

**Issue by kgstew** [reallocate/reallocate#83]
When creating a new project and entering the organization information. I entered ReAllocate and the page let me know that the organization already exists. In this case the system should allow the user to select the organization from a drop down list so they can move onto the next step.

**Comment by scottzer0** [comment]
assigning this to Haroun.  i'll leave it to him to decide how he wants the list or orgs fed to him.  i'm happy to whip up an ajax handler or can also hack a list into the template on initial request.

**Comment by scottzer0** [comment]
organization fields are currently used in:
- new_organization.html
- profile.html
- manage_project.html

**Comment by hserang** [comment]
Working prototype in feature/autocomplete for /organization/new/ only at the moment. 

Made a bunch of optimizations and bug fixes. Set up MVVM so we can update the form by adding an ajax call from the model and have the form auto-populate.

The UX is missing a full form autofill with project data on blur. Will work with Scott on this.
