### ISSUE TITLE
Add delete function for opportunities

### ISSUE THREAD

**Issue by kgstew** [reallocate/reallocate#85]
The delete button for opportunities on the project management page is currently a link to the view opportunity page. 

This button should open a modal asking if you really want to delete the opportunity and then allow yes to delete the opportunity or no to go back to the project management page.

**Comment by scottzer0** [comment]
not reproducing this and closing.  reopen if a edge case is rediscovered with more specific description

**Comment by kgstew** [comment]
Clicking the delete opportunity button from the project management page opens a confirmation dialog asking if you really want to delete the opportunity. After clicking yes the dialog disappears but the opportunity remains. Opportunities should be removed once they are deleted.
